--- 
site: Brian G.
tagline: Christian, husband, front-end web developer & designer working and living in the City of Angels.
ga: UA-5991707-2
twitter: brianmgonzalez
repo_url: git@github.com:briangonzalez/briangonzalez.org.git
authorized_users: 
  brian: b419dc186c1a9d5ea75aeefbfa6537a5
google_fonts_families:
  - Lato:300,400,700,900
root_path: ' /home'
nav: 
  Home: " /home"
  About: " /about"
  Twitter: http://twitter.com/brianmgonzalez
  Github: http://github.com/briangonzalez
  Codepen: http://codepen.io/briangonzalez