--- 
site: Brian G.
tagline: Christian, husband, front-end web developer & designer working and living in the City of Angels.
ga: UA-5991707-2
twitter: brianmgonzalez
repo_url: git@github.com:briangonzalez/briangonzalez.org.git
authorized_users: 
  brian: 266052442b061694afa44a1376dfb05e
google_fonts_families:
  - Lato:300,300italic,400,400italic,700,900
root_path: ' /home'
nav: 
  Home: " /home"
  About: " /about"
  Twitter: http://twitter.com/brianmgonzalez
  Github: http://github.com/briangonzalez
  Codepen: http://codepen.io/briangonzalez
  Dribbble: http://dribbble.com/brianmgonzalez